<a href="https://colab.research.google.com/github/AllamElsheikh/Deep-learing-series-/blob/main/project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The project 1 in the DEEP_LEARNING_SERIES_BY_ALLAM_ELSHEIKH



    MNIST data set
    the problem ==> Hand-written digit classification .

this notebook is basic ...
it is the "Hellow world " in Deep learning

In [ ]:
#importing the libraries and dataset
import keras
import tensorflow as tf

from keras.datasets import mnist

In [ ]:
(x_train , y_train ) , (x_test , y_test ) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


i will take .2 of the data samples to be fast in *runnig*

In [ ]:
import random
num = int(.2 * len(x_train))
random.seed(42)
samples_train = random.sample(range(len(x_train)) , num)

x_train_sub = x_train[samples_train]
y_train_sub = y_train[samples_train]


In [ ]:
print(x_train_sub.shape)

y_train_sub.shape

(12000, 28, 28)


(12000,)

In [ ]:
x_train_sub[5]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 255, 191, 128, 128,
          0,   0,   0,  64, 128, 255,  64,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 255, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 191,  64,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 128, 255, 255, 255,
        255, 255, 255, 255, 255, 255, 255, 191,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  64, 191, 255,
        255, 255, 255, 255, 255, 255, 255, 255,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  64, 128, 191, 255, 255, 255, 255,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0, 128, 255, 255, 255, 128,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  64, 255, 255, 255, 255,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0, 255, 255, 255, 255, 191,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0, 128, 255, 255, 255, 255, 128,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         64, 255, 255, 255, 255, 255,  64,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
        191, 255, 255, 255, 255,  64,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 128,
        255, 255, 255, 255, 255,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  64, 255,
        255, 255, 255, 255,  64,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  64, 191, 255,
        255, 255, 255, 128,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 128, 255, 255,
        255, 255, 255,  64,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 255, 255, 255,
        255, 255,  64,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 191, 255, 255, 255,
        255, 191,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 255, 255, 255, 255,
        255,  64,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   

converting the images to array

In [ ]:
x_train_sub_1 = x_train_sub.reshape(12000 , 28*28).astype('float32')
x_test_1 = x_test.reshape(10000 , 28*28).astype('float32')

In [ ]:
x_train_sub_1[5]

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   

In [ ]:
y_train[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

converting each index to binary array

In [ ]:
from keras.utils import to_categorical
y_train_cat = to_categorical(y_train_sub)
y_test_cat = to_categorical(y_test)


In [ ]:
y_train_cat[:5]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

**build the network**

In [ ]:
from keras import layers , models

network = models.Sequential([
    layers.Dense(512 , activation='relu', input_shape = (28*28,)) ,
    layers.Dense(10 , activation='softmax')
])

**compiling the network**

In [ ]:
from keras import optimizers , losses
network.compile(
        optimizer= 'rmsprop',
        loss = losses.categorical_crossentropy ,
        metrics= ['accuracy']
)

**train the network**

In [ ]:
network.fit(x_train_sub_1 , y_train_cat , epochs= 5 , batch_size= 128)


Epoch 1/5
94/94 [==============================] - 1s 9ms/step - loss: 1.4520 - accuracy: 0.9457
Epoch 2/5
94/94 [==============================] - 1s 8ms/step - loss: 0.8824 - accuracy: 0.9589
Epoch 3/5
94/94 [==============================] - 1s 8ms/step - loss: 0.6218 - accuracy: 0.9677
Epoch 4/5
94/94 [==============================] - 1s 9ms/step - loss: 0.5144 - accuracy: 0.9721
Epoch 5/5
94/94 [==============================] - 1s 8ms/step - loss: 0.3848 - accuracy: 0.9793


let's evaluate the network

In [ ]:
network.evaluate(x_test_1 , y_test_cat)

313/313 [==============================] - 1s 2ms/step - loss: 1.5489 - accuracy: 0.9509


[1.548889398574829, 0.9509000182151794]

good accuracy for now
-----------------------------------------------
try it yourself


# By ALLAM elsheikh